# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # This is to update requirements.txt files in the guided-demos, and e2e directories.
  # The group configuration option is used to group updates for consistency across related directories.
  - package-ecosystem: "pip"
    directories:
      - "**/demo-notebooks/guided-demos*"
      - "/tests/e2e"
    schedule:
      interval: "weekly"
    groups:
      requirements.txt:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "test-guided-notebooks"

  # We can not bump dependencies for poetry.lock and pyproject.toml files without 
  # also creating multiple PRs for custom-nb-image/requirements.txt file.
  # Dependabot does not yet offer the feature neither a workaround to exclude directories.
  # Issue: https://github.com/dependabot/dependabot-core/issues/4364
