# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # pip means poetry in this case, this keeps poetry.lock up to date with constraints in pyproject.toml.
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "**/demo-notebooks/guided-demos*"
      - "/tests/e2e"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - test-guided-notebooks
