version: 2
updates:
# pip means poetry in this case, this keeps poetry.lock up to date with constraints in pyproject.toml.
- package-ecosystem: pip
  directories:
    - "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  labels:
    - test-guided-notebooks
# This is to update requirements.txt files in the guided-demos, and e2e directories.
# The group configuration option is used to group updates for consistency across related directories.
- package-ecosystem: pip
  directories:
    - "**/demo-notebooks/guided-demos*"
    - "/tests/e2e"
  schedule:
    interval: "weekly"
  groups:
    requirements.txt:
      patterns:
        - "*"
  open-pull-requests-limit: 10
  labels:
    - test-guided-notebooksss
# Workaround to exclude upgrading dependencies in the custom-nb-image directory.
# Issue: https://github.com/dependabot/dependabot-core/issues/4364
- package-ecosystem: pip
  directory: /custom-nb-image
  target-branch: main
  schedule:
    interval: "weekly"
  labels: [ ]
  ignore:
    - dependency-name: "*" # Ignore all dependencies
