# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # This is to update requirements.txt files in the guided-demos, and e2e directories.
  - package-ecosystem: "pip"
    directories:
      - "**/demo-notebooks/guided-demos*"
      - "/tests/e2e"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 4
    labels:
      - "test-guided-notebooks"

  # pip means poetry in this case, this keeps poetry.lock up to date with constraints in pyproject.toml.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 1
    labels:
      - "test-guided-notebooks"

  # npm means yarn in this case, this keeps yarn.lock up to date with constraints in package.json.
  - package-ecosystem: "npm"
    directory: "/ui-tests"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 1
    labels:
      - "test-ui-notebooks"
