apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: example-raycluster
spec:
  rayVersion: "1.0.1"
  headGroupSpec:
    replicas: 1
    rayStartParams:
      port: "6379"
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:1.0.1
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "ray start --head --node-ip-address=$MY_POD_IP --port=6379 --dashboard-host=0.0.0.0" ]
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
  workerGroupSpecs:
  - groupName: worker-group-1
    replicas: 1
    maxReplicas: 2
    minReplicas: 1
    rayStartParams:
      port: "6379"
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:1.0.1
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "ray start --address=$RAY_HEAD_SERVICE_HOST:6379" ]
