# This workflow file adds the 'lgtm' and 'approved' labels to Dependabot PRs
# This is done to ensure that the PRs that pass e2e are automatically merged/added to merge-queues by the CodeFlare bot
name: Dependabot Labeler

on:
  pull_request:

jobs:
    add-approve-lgtm-label:
        if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependabot')
        runs-on: ubuntu-latest
        steps:
            - name: Add approve and lgtm labels to Dependabot PR
              run: |
                  gh pr edit ${{ github.event.pull_request.number }} --add-label "lgtm" --add-label "approved"
              env:
                GITHUB_TOKEN: ${{ secrets.CODEFLARE_MACHINE_ACCOUNT_TOKEN }}
